// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qqgpukatbbekdsyihnfe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFxZ3B1a2F0YmJla2RzeWlobmZlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTczMzU2NjcsImV4cCI6MjA3MjkxMTY2N30.IuA4NMcbTMeLCKvCP76CL45YeS7TOOySAzZkT6nYiWw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});